:: Name:     advies.cmd 
:: Purpose:  Set required environment and run test script 
:: Author:   Generated by script 
:: 
@ECHO off 
SETLOCAL ENABLEEXTENSIONS 
:: 
:: Setting required environment variables: 
:: 
SET site_name_base=labyrint-coaching.nl 
ECHO labyrint-coaching.nl 
CALL test_sitemap.cmd 
 
