:: Name:     alpacafarm.cmd 
:: Purpose:  Set required environment and run test script 
:: Author:   Generated by script 
:: 
@ECHO off 
SETLOCAL ENABLEEXTENSIONS 
:: 
:: Setting required environment variables: 
:: 
SET site_name_base=alpacafarm-in-de-puthof.nl 
ECHO alpacafarm-in-de-puthof.nl 
CALL test_sitemap.cmd 
 
