:: Name:     voluntas.cmd 
:: Purpose:  Set required environment and run test script 
:: Author:   Generated by script 
:: 
@ECHO off 
SETLOCAL ENABLEEXTENSIONS 
:: 
:: Setting required environment variables: 
:: 
SET site_name_base=voluntas.nl 
ECHO voluntas.nl 
CALL test_sitemap.cmd 
 
