:: Name:     baseline.cmd 
:: Purpose:  Set required environment and run test script 
:: Author:   Generated by script 
:: 
@ECHO off 
SETLOCAL ENABLEEXTENSIONS 
:: 
:: Setting required environment variables: 
:: 
SET site_name_base=v01-baseline-free.ipheion.eu 
ECHO v01-baseline-free.ipheion.eu 
CALL test_site_redirect.cmd 
 
