:: Name:     2connect4u.cmd 
:: Purpose:  Set required environment and run test script 
:: Author:   Generated by script 
:: 
@ECHO off 
SETLOCAL ENABLEEXTENSIONS 
:: 
:: Setting required environment variables: 
:: 
SET site_name_base=2connect4u.nl 
ECHO 2connect4u.nl 
CALL test_site_headers.cmd 
 
