:: Name:     batch_test.cmd 
:: Purpose:  Set required environment and run test script 
:: Author:   Generated by script 
:: 
@ECHO off 
SETLOCAL ENABLEEXTENSIONS 
:: 
:: Setting required environment variables: 
:: 
SET site_name_base=pvln.nl 
ECHO pvln.nl 
CALL test_site_headers.cmd 
:: 
SET site_name_base=initial.pvln.nl 
ECHO initial.pvln.nl 
CALL test_site_headers.cmd 
:: 
SET site_name_base=mgmt.pvln.nl 
ECHO mgmt.pvln.nl 
CALL test_site_headers.cmd 
:: 
SET site_name_base=2connect4u.nl 
ECHO 2connect4u.nl 
CALL test_site_headers.cmd 
:: 
SET site_name_base=ver-bind.nl 
ECHO ver-bind.nl 
CALL test_site_headers.cmd 
:: 
SET site_name_base=voluntas.nl 
ECHO voluntas.nl 
CALL test_site_headers.cmd 
:: 
SET site_name_base=alpacafarm-in-de-puthof.nl 
ECHO alpacafarm-in-de-puthof.nl 
CALL test_site_headers.cmd 
:: 
SET site_name_base=praktijkozitdatzo.nl 
ECHO praktijkozitdatzo.nl 
CALL test_site_headers.cmd 
:: 
SET site_name_base=labyrint-therapie.nl 
ECHO labyrint-therapie.nl 
CALL test_site_headers.cmd 
:: 
SET site_name_base=labyrint-coaching.nl 
ECHO labyrint-coaching.nl 
CALL test_site_headers.cmd 
:: 
SET site_name_base=labyrint-advies.nl 
ECHO labyrint-advies.nl 
CALL test_site_headers.cmd 
:: 
SET site_name_base=trappswise.nl 
ECHO trappswise.nl 
CALL test_site_headers.cmd 
:: 
SET site_name_base=ipheion.eu 
ECHO ipheion.eu 
CALL test_site_headers.cmd 
:: 
SET site_name_base=ipheion.nl 
ECHO ipheion.nl 
CALL test_site_headers.cmd 
:: 
SET site_name_base=reflect-ing.nl 
ECHO reflect-ing.nl 
CALL test_site_headers.cmd 
:: 
SET site_name_base=v01-baseline-free.ipheion.eu 
ECHO v01-baseline-free.ipheion.eu 
CALL test_site_headers.cmd 
:: 
