:: Name:     ipheion-nl.cmd 
:: Purpose:  Set required environment and run test script 
:: Author:   Generated by script 
:: 
@ECHO off 
SETLOCAL ENABLEEXTENSIONS 
:: 
:: Setting required environment variables: 
:: 
SET site_name_base=ipheion.nl 
ECHO ipheion.nl 
CALL test_site_headers.cmd 
 
