:: Name:     reflect-ing.cmd 
:: Purpose:  Set required environment and run test script 
:: Author:   Generated by script 
:: 
@ECHO off 
SETLOCAL ENABLEEXTENSIONS 
:: 
:: Setting required environment variables: 
:: 
SET site_name_base=reflect-ing.nl 
ECHO reflect-ing.nl 
CALL test_site_headers.cmd 
 
