:: Name:     ver-bind.cmd 
:: Purpose:  Set required environment and run test script 
:: Author:   Generated by script 
:: 
@ECHO off 
SETLOCAL ENABLEEXTENSIONS 
:: 
:: Setting required environment variables: 
:: 
SET site_name_base=ver-bind.nl 
ECHO ver-bind.nl 
CALL test_site_headers.cmd 
 
